#!/bin/sh
#
# @name Katech VTOL H 0604 Real Flight
#
# @type Octorotor h
# @class Copter
#
# @maintainer KL
#
#
# @output Motor1 motor 1
# @output Motor2 motor 2
# @output Motor3 motor 3
# @output Motor4 motor 4
# @output Motor5 motor 5
# @output Motor6 motor 6
# @output Motor7 motor 7
# @output Motor8 motor 8

. ${R}etc/init.d/rc.mc_defaults



# param set-default BAT1_N_CELLS 3
param set-default MAV_TYPE 14
# param set-default mot_kv 110           # Motor Kv constant (RPM per volt)
param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 8
param set-default CA_ROTOR0_PX 0.46     # Position X for rotor 0 (m)
param set-default CA_ROTOR0_PY 0.16    # Position Y for rotor 0 (m)
param set-default CA_ROTOR0_PZ 0.0    # Position Z for rotor 0 (m)
param set-default CA_ROTOR0_KM -0.29    # Moment coefficient KM for rotor 0 (Torque = KM * Thrust)
# param set-default CA_ROTOR0_CT 0.0005   # Thrust coefficient CT for rotor 0 (Thrust = CT * u)

param set-default CA_ROTOR1_PX -0.46
param set-default CA_ROTOR1_PY -0.16
param set-default CA_ROTOR1_PZ -0.1
param set-default CA_ROTOR1_KM -0.29
# param set-default CA_ROTOR1_CT 0.0005

param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY 0.16
param set-default CA_ROTOR2_PZ 0.0
param set-default CA_ROTOR2_KM 0.29
# param set-default CA_ROTOR2_CT 0.0005

param set-default CA_ROTOR3_PX -0.46
param set-default CA_ROTOR3_PY 0.16
param set-default CA_ROTOR3_PZ 0.0
param set-default CA_ROTOR3_KM 0.29
# param set-default CA_ROTOR3_CT 0.0005

param set-default CA_ROTOR4_PX 0.46
param set-default CA_ROTOR4_PY -0.16
param set-default CA_ROTOR4_PZ -0.1
param set-default CA_ROTOR4_KM 0.29
# param set-default CA_ROTOR4_CT 0.0005

param set-default CA_ROTOR5_PX -0.15
param set-default CA_ROTOR5_PY -0.16
param set-default CA_ROTOR5_PZ -0.1
param set-default CA_ROTOR5_KM 0.29
# param set-default CA_ROTOR5_CT 0.0005

param set-default CA_ROTOR6_PX 0.15
param set-default CA_ROTOR6_PY -0.16
param set-default CA_ROTOR6_PZ -0.1
param set-default CA_ROTOR6_KM -0.29
# param set-default CA_ROTOR6_CT 0.0005

param set-default CA_ROTOR7_PX -0.15
param set-default CA_ROTOR7_PY 0.16
param set-default CA_ROTOR7_PZ 0.0
param set-default CA_ROTOR7_KM -0.29
# param set-default CA_ROTOR7_CT 0.0005

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108

param set-default PWM_MAIN_MIN1 1000
param set-default PWM_MAIN_MIN2 1000
param set-default PWM_MAIN_MIN3 1000
param set-default PWM_MAIN_MIN4 1000
param set-default PWM_MAIN_MIN5 1000
param set-default PWM_MAIN_MIN6 1000
param set-default PWM_MAIN_MIN7 1000
param set-default PWM_MAIN_MIN8 1000

param set-default PWM_MAIN_MAX1 2000
param set-default PWM_MAIN_MAX2 2000
param set-default PWM_MAIN_MAX3 2000
param set-default PWM_MAIN_MAX4 2000
param set-default PWM_MAIN_MAX5 2000
param set-default PWM_MAIN_MAX6 2000
param set-default PWM_MAIN_MAX7 2000
param set-default PWM_MAIN_MAX8 2000
