#ifndef FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C__VISIBILITY_CONTROL_H_
#define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_EXPORT __attribute__ ((dllexport))
    #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_IMPORT __attribute__ ((dllimport))
  #else
    #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_EXPORT __declspec(dllexport)
    #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_IMPORT __declspec(dllimport)
  #endif
  #ifdef FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_BUILDING_LIBRARY
    #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_PUBLIC FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_EXPORT
  #else
    #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_PUBLIC FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_IMPORT
  #endif
  #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_PUBLIC_TYPE FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_PUBLIC
  #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_LOCAL
#else
  #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_EXPORT __attribute__ ((visibility("default")))
  #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_IMPORT
  #if __GNUC__ >= 4
    #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_PUBLIC __attribute__ ((visibility("default")))
    #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_PUBLIC
    #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_LOCAL
  #endif
  #define FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C_PUBLIC_TYPE
#endif
#endif  // FLIGHT_DATA_COLLECTION_50HZ_CONVER_TO_C__VISIBILITY_CONTROL_H_
// Generated 04-Dec-2025 16:19:26
// Copyright 2019-2020 The MathWorks, Inc.
