clear all; clc; close all;

% 데이터 불러오기
data = readtable('/home/hmcl/PX4_testbed/octocopter_matlab/drone_metric_matlab/flight_data_for_agressive_maneuver_v1.csv', 'VariableNamingRule', 'preserve');

% 변수 추출
p = data.p; u_p = data.u_p; backward_Mx = data.backward_Mx;
q = data.q; u_q = data.u_q; backward_My = data.backward_My;
r = data.r; u_r = data.u_r; backward_Mz = data.backward_Mz;

% 스텝와이즈 회귀에서 얻은 최종 모델 계수
coeffs_backward_Mx = struct( ...
    'Intercept', -0.040724, ...
    'p', 1.9135, ...
    'u_p', 24.05, ...
    'p_u_p', -225.31 ...
);

coeffs_backward_My = struct( ...
    'Intercept', -0.0096451, ...
    'q', 0.9409, ...
    'u_q', 1.401, ...
    'q_u_q', 2.9968 ...
);

coeffs_backward_Mz = struct( ...
    'Intercept', -0.23607, ...
    'r', -0.13556, ...
    'u_r', 16.126, ...
    'r_squared', 0.32136, ...
    'u_r_squared', -12.546 ...
);

% 1. p와 u_p 분석 (backward_Mx)
figure;
scatter3(p, u_p, backward_Mx, 20, 'filled', 'MarkerFaceColor', 'b');
hold on;
[p_mesh, u_p_mesh] = meshgrid( ...
    linspace(min(p), max(p), 50), ...
    linspace(min(u_p), max(u_p), 50) ...
);
backward_Mx_mesh = coeffs_backward_Mx.Intercept + ...
                   coeffs_backward_Mx.p * p_mesh + ...
                   coeffs_backward_Mx.u_p * u_p_mesh + ...
                   coeffs_backward_Mx.p_u_p * p_mesh .* u_p_mesh;
surf(p_mesh, u_p_mesh, backward_Mx_mesh, 'EdgeColor', 'none', 'FaceAlpha', 0.5, 'FaceColor', 'r');
xlabel('p (Roll Rate)'); ylabel('u_p (Control Input)'); zlabel('backward Mx');
title('3D Scatter and Regression Plane for backward Mx');
grid on;
hold off;

% 2. q와 u_q 분석 (backward_My)
figure;
scatter3(q, u_q, backward_My, 20, 'filled', 'MarkerFaceColor', 'b');
hold on;
[q_mesh, u_q_mesh] = meshgrid( ...
    linspace(min(q), max(q), 50), ...
    linspace(min(u_q), max(u_q), 50) ...
);
backward_My_mesh = coeffs_backward_My.Intercept + ...
                   coeffs_backward_My.q * q_mesh + ...
                   coeffs_backward_My.u_q * u_q_mesh + ...
                   coeffs_backward_My.q_u_q * q_mesh .* u_q_mesh;
surf(q_mesh, u_q_mesh, backward_My_mesh, 'EdgeColor', 'none', 'FaceAlpha', 0.5, 'FaceColor', 'r');
xlabel('q (Pitch Rate)'); ylabel('u_q (Control Input)'); zlabel('backward My');
title('3D Scatter and Regression Plane for backward My');
grid on;
hold off;

% 3. r와 u_r 분석 (backward_Mz)
figure;
scatter3(r, u_r, backward_Mz, 20, 'filled', 'MarkerFaceColor', 'b');
hold on;
[r_mesh, u_r_mesh] = meshgrid( ...
    linspace(min(r), max(r), 50), ...
    linspace(min(u_r), max(u_r), 50) ...
);
backward_Mz_mesh = coeffs_backward_Mz.Intercept + ...
                   coeffs_backward_Mz.r * r_mesh + ...
                   coeffs_backward_Mz.u_r * u_r_mesh + ...
                   coeffs_backward_Mz.r_squared * r_mesh.^2 + ...
                   coeffs_backward_Mz.u_r_squared * u_r_mesh.^2;
surf(r_mesh, u_r_mesh, backward_Mz_mesh, 'EdgeColor', 'none', 'FaceAlpha', 0.5, 'FaceColor', 'r');
xlabel('r (Yaw Rate)'); ylabel('u_r (Control Input)'); zlabel('backward Mz');
title('3D Scatter and Regression Plane for backward Mz');
grid on;
hold off;
