clear all; clc; close all;

% 데이터 불러오기
data = readtable('/home/hmcl/PX4_testbed/octocopter_matlab/drone_metric_matlab/flight_data_for_agressive_maneuver.csv', 'VariableNamingRule', 'preserve');

% 변수 추출
p = data.p; u_p = data.u_p; Mx_actual = data.Mx;
q = data.q; u_q = data.u_q; My_actual = data.My;
r = data.r; u_r = data.u_r; Mz_actual = data.Mz;

% 계수 정의 (Mx, My, Mz 각각)
coeffs_Mx = struct( ...
    'p', 3.7765, ...
    'u_p', 21.757, ...
    'p_up', -1508.3, ...
    'p_squared', -7.9738, ...
    'constant', 0.091002);

coeffs_My = struct( ...
    'q', 1.3502, ...
    'u_q', -0.073419, ...
    'q_uq', -76.175, ...
    'constant', -0.015016);

coeffs_Mz = struct( ...
    'r', 1.0822, ...
    'u_r', 17.142, ...
    'r_squared', 0.20905, ...
    'u_r_squared', -20.001, ...
    'constant', 0.020245);

% 1. p와 u_p 분석 (Mx)
figure;
scatter3(p, u_p, Mx_actual, 20, 'filled', 'MarkerFaceColor', 'b', 'DisplayName', 'Actual Mx Data');
hold on;
[p_mesh, u_p_mesh] = meshgrid( ...
    linspace(min(p)-0.1*abs(min(p)), max(p)+0.1*abs(max(p)), 50), ...
    linspace(min(u_p)-0.1*abs(min(u_p)), max(u_p)+0.1*abs(max(u_p)), 50) ...
);
Mx_mesh = coeffs_Mx.p * p_mesh + coeffs_Mx.u_p * u_p_mesh ...
        + coeffs_Mx.p_up * p_mesh .* u_p_mesh ...
        + coeffs_Mx.p_squared * p_mesh.^2 ...
        + coeffs_Mx.constant;
surf(p_mesh, u_p_mesh, Mx_mesh, 'EdgeColor', 'none', 'FaceAlpha', 0.5, ...
    'FaceColor', 'r', 'DisplayName', 'Regression Plane for Mx');
xlabel('p (Roll Rate)');
ylabel('u_p (Control Input)');
zlabel('Mx (Predicted/Actual)');
title('3D Scatter and Regression Plane for Mx');
legend('Location', 'best');
grid on;
hold off;

% 2. q와 u_q 분석 (My)
figure;
scatter3(q, u_q, My_actual, 20, 'filled', 'MarkerFaceColor', 'b', 'DisplayName', 'Actual My Data');
hold on;
[q_mesh, u_q_mesh] = meshgrid( ...
    linspace(min(q)-0.1*abs(min(q)), max(q)+0.1*abs(max(q)), 50), ...
    linspace(min(u_q)-0.1*abs(min(u_q)), max(u_q)+0.1*abs(max(u_q)), 50) ...
);
My_mesh = coeffs_My.q * q_mesh + coeffs_My.u_q * u_q_mesh ...
        + coeffs_My.q_uq * q_mesh .* u_q_mesh ...
        + coeffs_My.constant;
surf(q_mesh, u_q_mesh, My_mesh, 'EdgeColor', 'none', 'FaceAlpha', 0.5, ...
    'FaceColor', 'r', 'DisplayName', 'Regression Plane for My');
xlabel('q (Pitch Rate)');
ylabel('u_q (Control Input)');
zlabel('My (Predicted/Actual)');
title('3D Scatter and Regression Plane for My');
legend('Location', 'best');
grid on;
hold off;

% 3. r와 u_r 분석 (Mz)
figure;
scatter3(r, u_r, Mz_actual, 20, 'filled', 'MarkerFaceColor', 'b', 'DisplayName', 'Actual Mz Data');
hold on;
[r_mesh, u_r_mesh] = meshgrid( ...
    linspace(min(r)-0.1*abs(min(r)), max(r)+0.1*abs(max(r)), 50), ...
    linspace(min(u_r)-0.1*abs(min(u_r)), max(u_r)+0.1*abs(max(u_r)), 50) ...
);
Mz_mesh = coeffs_Mz.r * r_mesh + coeffs_Mz.u_r * u_r_mesh ...
        + coeffs_Mz.r_squared * r_mesh.^2 ...
        + coeffs_Mz.u_r_squared * u_r_mesh.^2 ...
        + coeffs_Mz.constant;
surf(r_mesh, u_r_mesh, Mz_mesh, 'EdgeColor', 'none', 'FaceAlpha', 0.5, ...
    'FaceColor', 'r', 'DisplayName', 'Regression Plane for Mz');
xlabel('r (Yaw Rate)');
ylabel('u_r (Control Input)');
zlabel('Mz (Predicted/Actual)');
title('3D Scatter and Regression Plane for Mz');
legend('Location', 'best');
grid on;
hold off;
